# Generated by Django 5.1.1 on 2024-09-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_card_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
