# Generated by Django 5.1.1 on 2024-09-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_user_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_for_usage',
            field=models.CharField(default='useradmin', max_length=250),
            preserve_default=False,
        ),
    ]
